# Generated by Django 4.2.25 on 2025-10-19 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró la compra')),
                ('fecha_visita', models.DateField(help_text='Fecha elegida por el visitante para ir al parque')),
                ('monto_total', models.DecimalField(decimal_places=2, help_text='Costo total calculado de todas las entradas', max_digits=10)),
                ('forma_pago', models.CharField(choices=[('EFE', 'Efectivo en Boletería'), ('TAR', 'Tarjeta (Mercado Pago)')], help_text='Método de pago seleccionado', max_length=3)),
                ('estado_pago', models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('CAN', 'Cancelado')], default='PEN', help_text='Estado actual del pago', max_length=3)),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la compra', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Pase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de pase', max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio del tipo de pase', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad_visitante', models.PositiveIntegerField(help_text='Edad del visitante')),
                ('precio_calculado', models.DecimalField(decimal_places=2, help_text='Precio final de esta entrada', max_digits=8)),
                ('compra', models.ForeignKey(help_text='Compra a la que pertenece esta entrada', on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='entradas.compra')),
                ('pase', models.ForeignKey(help_text='Tipo de pase adquirido', on_delete=django.db.models.deletion.PROTECT, related_name='entradas_vendidas', to='entradas.pase')),
            ],
        ),
    ]
